jury:
  - "player1"
  - "player2"
  - "player3"
  - "player4"
  - "player5"

locations:
  seekers: {}
  hiders: {}

settings:
  language: "ru_ru"  # Available: en_us, ru_ru
  hide-time: 300 # 5 minutes in seconds
  seek-time: 600 # 10 minutes in seconds
  glow-time: 30 # Last 30 seconds glow time
  max-players: 24 