name: HideAndSeek
version: '2.0'
main: io.github.hideAndSeek.HideAndSeek
api-version: '1.20'
authors: [Faustyu]
description: Hide and Seek minigame plugin
commands:
  hideandseek:
    description: Main command for Hide and Seek game
    usage: |
      /<command> start - Start the game
      /<command> setseek - Set seekers spawn point
      /<command> sethiders - Set hiders spawn point
      /<command> language <en_us|ru_ru> - Change language
    permission: hideandseek.admin
permissions:
  hideandseek.admin:
    description: Allows access to all Hide and Seek commands
    default: op
